#!/usr/bin/env python
"""分析固定时间抽帧和MOG2弱信号机制"""

print("=" * 70)
print("固定时间抽帧和MOG2弱信号机制分析")
print("=" * 70)
print()

print("1. 固定时间抽帧配置")
print("=" * 70)
print()
print("配置位置: traffic_vlm/config.py")
print("参数名: always_sample_interval_seconds")
print("默认值: 8.0 秒")
print()
print("这个参数的作用:")
print("  - 每隔8秒强制抽取一个关键帧")
print("  - 即使没有检测到运动也会抽取")
print("  - 作为'背景关键帧'用于对照")
print("  - 保证召回率，避免遗漏重要场景")
print()

print("2. MOG2/帧差弱信号机制")
print("=" * 70)
print()
print("实现位置: traffic_vlm/motion_detector.py")
print()
print("关键代码 (第94-103行):")
print("""
    # 强制采样（弱信号兜底）
    if timestamp - self.last_force_ts >= self.config.always_sample_interval_seconds:
        triggers.append(
            {
                "timestamp": timestamp,
                "score": max(score, 0.0),
                "type": "always_sample",
            }
        )
        self.last_force_ts = timestamp
""")
print()

print("3. 运动检测配置")
print("=" * 70)
print()
print("主要参数:")
print("  - motion_method: 'mog2' (默认)")
print("    * 使用MOG2背景减法")
print("    * 可选: 'frame_diff', 'none'")
print()
print("  - motion_min_fg_ratio: 0.02 (2%)")
print("    * 前景区域占画面比例的最小阈值")
print("    * 只有当运动区域 >= 2%时才考虑触发")
print()
print("  - motion_debounce_frames: 3")
print("    * 需要连续3帧满足条件才触发")
print("    * 避免误触发")
print()
print("  - always_sample_interval_seconds: 8.0")
print("    * 每8秒强制抽取一个关键帧")
print("    * 即使没有检测到运动也会抽取")
print()

print("4. 完整工作流程")
print("=" * 70)
print()
print("步骤1: 运动检测")
print("  - MOG2计算前景掩码")
print("  - 如果前景区域 >= 2%且连续3帧满足条件")
print("  - 标记为 'motion_mog2' 类型")
print()
print("步骤2: 强制抽帧（弱信号兜底）")
print("  - 每8秒强制抽取一个关键帧")
print("  - 标记为 'always_sample' 类型")
print("  - 即使没有检测到运动也会抽取")
print()
print("步骤3: 关键帧融合")
print("  - 合并 'motion_mog2' 和 'always_sample' 类型的关键帧")
print("  - 确保既有运动触发的关键帧，也有背景对照帧")
print("  - 提高检测召回率")
print()

print("5. 触发类型")
print("=" * 70)
print()
print("两种关键帧触发类型:")
print()
print("类型1: motion_mog2")
print("  - 由MOG2运动检测触发")
print("  - 条件: 前景区域 >= 2%且连续3帧")
print("  - 用途: 捕获明显的运动场景")
print()
print("类型2: always_sample")
print("  - 由固定时间间隔触发")
print("  - 间隔: 每8秒一次")
print("  - 用途: 提供背景对照，保证召回率")
print()

print("6. 配置示例")
print("=" * 70)
print()
print("如果你想修改固定时间间隔，可以编辑:")
print("  文件: traffic_vlm/config.py")
print("  参数: always_sample_interval_seconds: float = 8.0")
print()
print("推荐值:")
print("  - 5秒: 更密集的背景采样，适合变化快的场景")
print("  - 8秒: 当前默认值，平衡性能和召回率")
print("  - 10秒: 更稀疏的背景采样，节省存储空间")
print()

print("=" * 70)
print("总结")
print("=" * 70)
print()
print("当前设置:")
print("  ✓ 固定时间抽帧: 8秒")
print("  ✓ 运动检测方法: MOG2")
print("  ✓ 弱信号机制: 每8秒强制抽帧作为兜底")
print("  ✓ 触发类型: motion_mog2 + always_sample")
print()
print("这个设计完全符合文档要求:")
print("  ✓ MOG2/帧差仅作为'弱信号'")
print("  ✓ 每隔固定时间强制抽取背景关键帧")
print("  ✓ 保证召回率")
