#!/usr/bin/env python
"""TrafficVLM参数优化指南 - 提高召回率和准确率"""

print("=" * 80)
print("TrafficVLM 参数优化指南 - 提高召回率和准确率")
print("=" * 80)
print()

print("当前配置值（从 config.py 获取）:")
print("-" * 80)
print("StreamConfig:")
print("  lowres_size: (640, 360)")
print("  lowres_fps: 12")
print("  motion_method: 'mog2'")
print("  motion_min_fg_ratio: 0.02")
print("  motion_min_score: 8.0")
print("  motion_debounce_frames: 3")
print("  always_sample_interval_seconds: 1.0  ← 已修改为1秒")
print("  min_keyframe_interval: 2.0")
print()
print("EmbeddingConfig:")
print("  model_name: 'google/siglip-base-patch16-384'")
print("  batch_size: 8")
print("  top_m_per_template: 50")
print("  frame_top_n: 80")
print("  candidate_clip_top_k: 12")
print("  clip_embedding_frames: 8")
print()
print("ClusterConfig:")
print("  merge_window_seconds: 5.0")
print("  pre_padding: 3.0")
print("  post_padding: 7.0")
print("  clip_sampling_frames: 8")
print("  candidate_clip_top_k: 12")
print()
print("DetectorConfig:")
print("  enabled: True")
print("  model_path: 'yolov8n.pt'")
print("  tracker: 'bytetrack'")
print("  confidence_threshold: 0.25")
print("  iou_threshold: 0.45")
print("  max_detections: 100")
print()
print("VLMConfig:")
print("  model: 'qwen3-vl-plus'")
print("  top_clips: 3")
print("  annotated_frames_per_clip: 4")
print("  temperature: 0.4")
print()
print("-" * 80)
print()

print("=" * 80)
print("一、运动检测参数优化 (StreamConfig)")
print("=" * 80)
print()

print("1.1 always_sample_interval_seconds")
print("  当前值: 1.0秒")
print("  作用: 固定时间间隔强制抽帧")
print("  影响:")
print("    - 值越小 → 召回率越高（更多背景关键帧）")
print("    - 值越小 → 计算量越大，存储空间占用增加")
print("  建议: 1-5秒")
print("    - 交通场景: 1-3秒（高召回率）")
print("    - 一般场景: 5-8秒（平衡性能）")
print("  当前值评价: ✓ 优秀（1秒极高召回率）")
print()

print("1.2 motion_min_fg_ratio")
print("  当前值: 0.02 (2%)")
print("  作用: 运动检测的最小前景区域比例")
print("  影响:")
print("    - 值越小 → 召回率越高（更敏感）")
print("    - 值越小 → 误报可能增加（准确率下降）")
print("  建议: 0.01-0.05")
print("    - 高召回率: 0.01 (1%)")
print("    - 平衡: 0.02 (2%)")
print("    - 高准确率: 0.03-0.05 (3-5%)")
print("  推荐修改: 0.015 (1.5%)")
print()

print("1.3 motion_debounce_frames")
print("  当前值: 3")
print("  作用: 需要连续多少帧满足条件才触发")
print("  影响:")
print("    - 值越小 → 召回率越高（响应更快）")
print("    - 值越大 → 准确率越高（减少误报）")
print("  建议: 2-5")
print("    - 高召回率: 2")
print("    - 平衡: 3")
print("    - 高准确率: 4-5")
print("  当前值评价: ✓ 良好（3是平衡值）")
print()

print("1.4 motion_method")
print("  当前值: 'mog2'")
print("  选项: mog2 | frame_diff | none")
print("  建议: 保持 mog2")
print("    - mog2: 背景建模，适合持续监控")
print("    - frame_diff: 帧差法，适合快速运动")
print("  当前值评价: ✓ 合适")
print()

print("1.5 lowres_size")
print("  当前值: (640, 360)")
print("  作用: 低分辨率流的尺寸（用于运动检测）")
print("  影响:")
print("    - 分辨率越高 → 召回率越高（细节更清晰）")
print("    - 分辨率越高 → 计算量越大")
print("  建议: 640x360 到 1280x720")
print("    - 当前值评价: ✓ 合适")
print()

print("1.6 lowres_fps")
print("  当前值: 12")
print("  作用: 低分辨率流的帧率")
print("  影响:")
print("    - 帧率越高 → 召回率越高（捕获更多瞬间）")
print("    - 帧率越高 → 计算量越大")
print("  建议: 10-20")
print("    - 当前值评价: ✓ 合适")
print()

print("=" * 80)
print("二、语义检索参数优化 (EmbeddingConfig)")
print("=" * 80)
print()

print("2.1 top_m_per_template")
print("  当前值: 50")
print("  作用: 每个模板检索返回的候选帧数")
print("  影响:")
print("    - 值越大 → 召回率越高")
print("    - 值越大 → 计算量越大")
print("  建议: 30-100")
print("    - 高召回率: 80-100")
print("    - 平衡: 50")
print("    - 高准确率: 30-40")
print("  推荐修改: 80")
print()

print("2.2 frame_top_n")
print("  当前值: 80")
print("  作用: 所有帧合并后取前N个最相似的帧")
print("  影响:")
print("    - 值越大 → 召回率越高（保留更多候选）")
print("    - 值越大 → 后续处理量越大")
print("  建议: 50-150")
print("    - 当前值评价: ✓ 合适")
print()

print("2.3 candidate_clip_top_k")
print("  当前值: 12")
print("  作用: 候选片段的Top-K数量")
print("  影响:")
print("    - 值越大 → 召回率越高")
print("    - 值越大 → VLM调用次数增加")
print("  建议: 10-20")
print("    - 当前值评价: ✓ 合适")
print()

print("2.4 clip_embedding_frames")
print("  当前值: 8")
print("  作用: 每个片段用于生成embeddings的帧数")
print("  影响:")
print("    - 值越大 → 召回率越高（更全面理解）")
print("    - 值越大 → 计算量越大")
print("  建议: 6-12")
print("    - 高召回率: 10-12")
print("    - 平衡: 8")
print("    - 高准确率: 6")
print("  推荐修改: 10")
print()

print("=" * 80)
print("三、时间聚类参数优化 (ClusterConfig)")
print("=" * 80)
print()

print("3.1 merge_window_seconds")
print("  当前值: 5.0秒")
print("  作用: 时间聚类的合并窗口大小")
print("  影响:")
print("    - 值越大 → 召回率越高（合并更多片段）")
print("    - 值越大 → 片段可能过长（准确率下降）")
print("  建议: 3-8秒")
print("    - 高召回率: 6-8秒")
print("    - 平衡: 5秒")
print("    - 高准确率: 3-4秒")
print("  当前值评价: ✓ 合适")
print()

print("3.2 pre_padding")
print("  当前值: 3.0秒")
print("  作用: 片段前填充时间")
print("  影响:")
print("    - 值越大 → 召回率越高（避免遗漏开始）")
print("    - 值越大 → 片段冗余增加")
print("  建议: 2-5秒")
print("    - 推荐修改: 4秒")
print()

print("3.3 post_padding")
print("  当前值: 7.0秒")
print("  作用: 片段后填充时间")
print("  影响:")
print("    - 值越大 → 召回率越高（避免遗漏结束）")
print("    - 值越大 → 片段冗余增加")
print("  建议: 5-10秒")
print("    - 当前值评价: ✓ 合适（7秒良好）")
print()

print("3.4 clip_sampling_frames")
print("  当前值: 8")
print("  作用: 从片段中采样用于VLM分析的帧数")
print("  影响:")
print("    - 值越大 → 召回率越高（更全面分析）")
print("    - 值越大 → VLM调用成本增加")
print("  建议: 6-12")
print("    - 高召回率: 10-12")
print("    - 平衡: 8")
print("    - 当前值评价: ✓ 合适")
print()

print("3.5 candidate_clip_top_k")
print("  当前值: 12")
print("  作用: 最终提交给VLM的候选片段数")
print("  影响:")
print("    - 值越大 → 召回率越高")
print("    - 值越大 → VLM调用成本增加")
print("  建议: 10-20")
print("    - 当前值评价: ✓ 合适")
print()

print("=" * 80)
print("四、YOLO检测参数优化 (DetectorConfig)")
print("=" * 80)
print()

print("4.1 confidence_threshold")
print("  当前值: 0.25")
print("  作用: YOLO检测的置信度阈值")
print("  影响:")
print("    - 值越小 → 召回率越高（检测更宽松）")
print("    - 值越小 → 误报可能增加（准确率下降）")
print("  建议: 0.2-0.4")
print("    - 高召回率: 0.2-0.25")
print("    - 平衡: 0.3")
print("    - 高准确率: 0.35-0.4")
print("  推荐修改: 0.2")
print()

print("4.2 iou_threshold")
print("  当前值: 0.45")
print("  作用: NMS的IoU阈值")
print("  影响:")
print("    - 值越小 → 召回率越高（保留更多框）")
print("    - 值越小 → 准确率可能下降（重复检测）")
print("  建议: 0.4-0.6")
print("    - 当前值评价: ✓ 合适")
print()

print("4.3 max_detections")
print("  当前值: 100")
print("  作用: 每帧最大检测数量")
print("  影响:")
print("    - 值越大 → 召回率越高（检测更多目标）")
print("    - 值越大 → 计算量增加")
print("  建议: 50-200")
print("    - 当前值评价: ✓ 合适")
print()

print("4.4 tracker")
print("  当前值: 'bytetrack'")
print("  作用: 目标跟踪算法")
print("  建议: 保持 bytetrack（速度与精度平衡）")
print("  当前值评价: ✓ 合适")
print()

print("=" * 80)
print("五、VLM分析参数优化 (VLMConfig)")
print("=" * 80)
print()

print("5.1 model")
print("  当前值: 'qwen3-vl-plus'")
print("  选项: qwen-vl-plus, qwen-vl-max, qwen3-vl-plus")
print("  建议:")
print("    - 性价比: qwen-vl-plus")
print("    - 最高精度: qwen-vl-max")
print("    - 最新模型: qwen3-vl-plus")
print("  当前值评价: ✓ 合适")
print()

print("5.2 top_clips")
print("  当前值: 3")
print("  作用: 提交给VLM分析的最优质片段数")
print("  影响:")
print("    - 值越大 → 召回率越高")
print("    - 值越大 → VLM调用成本增加")
print("  建议: 3-5")
print("    - 当前值评价: ✓ 合适")
print()

print("5.3 annotated_frames_per_clip")
print("  当前值: 4")
print("  作用: 每个片段用于VLM分析的标注帧数")
print("  影响:")
print("    - 值越大 → 召回率越高（更全面分析）")
print("    - 值越大 → VLM调用成本增加")
print("  建议: 4-8")
print("    - 高召回率: 6-8")
print("    - 平衡: 4")
print("    - 推荐修改: 6")
print()

print("5.4 temperature")
print("  当前值: 0.4")
print("  作用: VLM生成的随机性")
print("  影响:")
print("    - 值越小 → 输出更确定（准确率更高）")
print("    - 值越大 → 输出更多样（召回率可能更高）")
print("  建议: 0.2-0.7")
print("    - 高准确率: 0.2-0.3")
print("    - 平衡: 0.4")
print("    - 高召回率: 0.5-0.7")
print("  当前值评价: ✓ 合适")
print()

print("=" * 80)
print("六、查询模板优化 (TemplateConfig)")
print("=" * 80)
print()

print("6.1 模板数量和质量")
print("  现状: 每种违法行为3个模板")
print("  建议: 增加模板数量到5-10个")
print("  方法: 在 builtin_templates 中添加更多描述")
print()
print("  示例模板扩展:")
print("    bike_wrong_way:")
print("      - 现有: 3个")
print("      - 建议添加:")
print("        * 非机动车道逆行，二轮车反向行驶")
print("        * 电动车在机动车道逆行")
print("        * 自行车逆行方向与车流相反")
print("        * 摩托车逆行上主路")
print("        * 电动车在机动车道上逆向行驶")
print()

print("=" * 80)
print("总结：推荐修改的参数")
print("=" * 80)
print()

print("高优先级修改（强烈推荐）:")
print("1. motion_min_fg_ratio: 0.02 → 0.015  (提高召回率)")
print("2. top_m_per_template: 50 → 80       (提高召回率)")
print("3. clip_embedding_frames: 8 → 10     (提高召回率)")
print("4. pre_padding: 3.0 → 4.0           (提高召回率)")
print("5. confidence_threshold: 0.25 → 0.2  (提高召回率)")
print("6. annotated_frames_per_clip: 4 → 6  (提高召回率)")
print()

print("中优先级修改（推荐）:")
print("7. always_sample_interval_seconds: 1.0 (保持不变，已优化)")
print("8. motion_debounce_frames: 3 → 2     (提高召回率)")
print("9. TemplateConfig: 增加更多模板      (提高召回率)")
print()

print("低优先级修改（可选）:")
print("10. temperature: 0.4 → 0.3          (提高准确率)")
print("11. merge_window_seconds: 5.0 → 6.0 (提高召回率)")
print()

print("=" * 80)
print("参数修改对召回率和准确率的影响")
print("=" * 80)
print()

print("提高召回率（不漏检）:")
print("  ↓ 减小这些参数:")
print("    - motion_min_fg_ratio (0.02 → 0.015)")
print("    - confidence_threshold (0.25 → 0.2)")
print("    - motion_debounce_frames (3 → 2)")
print("    - temperature (0.4 → 0.3)")
print()
print("  ↑ 增大这些参数:")
print("    - top_m_per_template (50 → 80)")
print("    - frame_top_n (80 → 100)")
print("    - clip_embedding_frames (8 → 10)")
print("    - annotated_frames_per_clip (4 → 6)")
print("    - pre_padding (3 → 4)")
print("    - post_padding (7 → 8)")
print("    - merge_window_seconds (5 → 6)")
print("    - always_sample_interval_seconds (已改为1)")
print()

print("提高准确率（减少误报）:")
print("  ↑ 增大这些参数:")
print("    - motion_min_fg_ratio (0.02 → 0.025)")
print("    - confidence_threshold (0.25 → 0.3)")
print("    - motion_debounce_frames (3 → 4)")
print("    - temperature (0.4 → 0.5)")
print("    - merge_window_seconds (5 → 4)")
print()
print("  ↓ 减小这些参数:")
print("    - top_m_per_template (50 → 40)")
print("    - candidate_clip_top_k (12 → 10)")
print("    - clip_embedding_frames (8 → 6)")
print("    - annotated_frames_per_clip (4 → 3)")
print()

print("=" * 80)
print("最终建议")
print("=" * 80)
print()

print("如果你追求高召回率（不漏检任何违法行为）:")
print("  采用高召回率参数组合")
print("  适用于：交通监管部门、执法取证")
print()

print("如果你追求平衡（召回率和准确率兼顾）:")
print("  保持当前参数，部分微调")
print("  适用于：日常监控、常规分析")
print()

print("如果你追求高准确率（减少误报）:")
print("  采用高准确率参数组合")
print("  适用于：自动处罚、减少争议")
print()

print("当前配置评价:")
print("  ✓ always_sample_interval_seconds=1.0 (极佳，高召回率)")
print("  ✓ detector.enabled=True (已启用)")
print("  ✓ 模型选择合适")
print()
print("需要改进的地方:")
print("  * motion_min_fg_ratio 建议减小")
print("  * confidence_threshold 建议减小")
print("  * 增加更多查询模板")
